In [3]:
pip install numpy


  Using cached numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
arr = np.array([2,3,4,5,6,7])
arr

array([2, 3, 4, 5, 6, 7])

In [5]:
arr.ndim

1

In [9]:
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)


6
(6,)
int64
8


In [10]:
zero = np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
eye = np.eye(4, dtype=int)
print(eye)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
arra1 = np.arange(0, 11, 2)
print(arra1)

[ 0  2  4  6  8 10]


In [24]:
print(arra1.reshape(2, 3))

[[ 0  2  4]
 [ 6  8 10]]


In [28]:
array2 =np.linspace(0, 1, 10)
print(array2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [39]:
array3 = np.random.rand(3, 4)
print(array3)

[[0.28979075 0.62157711 0.4134748  0.29116387]
 [0.78639633 0.9255015  0.65528728 0.94397234]
 [0.03189076 0.12269116 0.05994555 0.16031275]]


In [41]:
temp = np.floor(array3 * 10)
print(temp)

[[2. 6. 4. 2.]
 [7. 9. 6. 9.]
 [0. 1. 0. 1.]]


In [48]:
temp[0:2,0:3]

array([[2., 6., 4.],
       [7., 9., 6.]])

In [49]:
temp[1:3, 0:2]

array([[7., 9.],
       [0., 1.]])

In [51]:
for i in array3:
    print(i)

[0.28979075 0.62157711 0.4134748  0.29116387]
[0.78639633 0.9255015  0.65528728 0.94397234]
[0.03189076 0.12269116 0.05994555 0.16031275]


In [55]:
np.apply_along_axis(np.max, 1, array3)

array([0.62157711, 0.94397234, 0.16031275])

In [58]:
temp[temp < 6]

array([2., 4., 2., 0., 1., 0., 1.])

In [61]:
!pip install openpyxl 
from openpyxl import Workbook
from random import randint, choice

first = ["Aarav","Vivaan","Aditya","Arjun","Reyansh","Mohammed","Shahid","Ayaan","Rohan","Rahul","Priya","Sneha","Ananya","Pooja","Neha","Kavya","Ishita","Meera","Sana","Fatima"]
last = ["Sharma","Patel","Khan","Momin","Gupta","Joshi","Kulkarni","Shaikh","Deshmukh","Singh","Verma","Naik","Pawar","Jadhav","Shaikh"]

wb=Workbook()
ws=wb.active
ws.title="Students"
ws.append(["Sr. No.","Name","PRN","Result"])
for i in range(1,31):
    name=f"{choice(first)} {choice(last)}"
    prn=str(randint(202600000000,202699999999))
    result=choice(["Pass","Pass","Pass","Fail"])
    ws.append([i,name,prn,result])

path="/Student_Data_30.xlsx"
wb.save(path)

print(path)


/Student_Data_30.xlsx



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [66]:
import numpy as np

mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2 = np.array([[9, 8], [5, 4], [2, 1]])

np.concatenate((mat1, mat2), axis=1)

array([[1, 2, 3, 9, 8],
       [4, 5, 6, 5, 4],
       [7, 8, 9, 2, 1]])

In [ ]:
A = np.ones((3, 4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
B = np.zeros((3, 4))

In [69]:
np.vstack((A, B))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.hstack((A, B))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [73]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.hstack((A, B))

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

In [76]:
mat3 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9],[10, 11, 12],[13, 14, 15]])
mat3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [84]:
f,s,t = np.split(mat3, [1, 4], axis=0)
f

array([[1, 2, 3]])

In [85]:
s

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
t

array([[13, 14, 15]])

In [87]:
mat4 = np.arange(100).reshape(10, 10)
mat4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
np.save("mat4.txt", mat4)

In [90]:
loaded_mat4 = np.load("mat4.npy")
loaded_mat4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
pip install pandas

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.9 MB 13.0 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/9.9 MB 11.2 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 12.1 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 10.5 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [95]:
import pandas as pd
s = pd.Series([1, 3, 5, 0, 6, 8])
s

0    1
1    3
2    5
3    0
4    6
5    8
dtype: int64

In [98]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [99]:
s[0:3]

0    1
1    3
2    5
dtype: int64

In [100]:
s[[0,2]]

0    1
2    5
dtype: int64

In [102]:
s = pd.Series([1, 3, 5, 0, 6, 8], index=['a', 'b', 'c', 'd', 'e', 'f'])
s

a    1
b    3
c    5
d    0
e    6
f    8
dtype: int64

In [103]:
s[0] = 10
s

a     1
b     3
c     5
d     0
e     6
f     8
0    10
dtype: int64

In [104]:
s

a     1
b     3
c     5
d     0
e     6
f     8
0    10
dtype: int64

In [1]:
from random import random
data = [random.randint(1, 100) for i in range(100)]

AttributeError: 'builtin_function_or_method' object has no attribute 'randint'